version: '3'
services:
  mmx:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: mmx
    mem_limit: 512m
    mem_reservation: 128M
    cpus: '0.05'
    ports:
      - 8080:80
    volumes:
      - .:/app/mmx
    links:
      - mariadb
  mariadb:
    image: yobasystems/alpine-mariadb:latest
    mem_limit: 512m
    mem_reservation: 128M
    cpus: '0.05'
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: docker